#define	MULTIPROCESSOR	1
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_MULTIPROCESSOR
 .global _KERNEL_OPT_MULTIPROCESSOR
 .equiv _KERNEL_OPT_MULTIPROCESSOR,0x1
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_MULTIPROCESSOR\n .global _KERNEL_OPT_MULTIPROCESSOR\n .equiv _KERNEL_OPT_MULTIPROCESSOR,0x1\n .endif");
#endif
