#define	BUFQ_PRIOCSCAN	1
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_BUFQ_PRIOCSCAN
 .global _KERNEL_OPT_BUFQ_PRIOCSCAN
 .equiv _KERNEL_OPT_BUFQ_PRIOCSCAN,0x1
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_BUFQ_PRIOCSCAN\n .global _KERNEL_OPT_BUFQ_PRIOCSCAN\n .equiv _KERNEL_OPT_BUFQ_PRIOCSCAN,0x1\n .endif");
#endif
