/* option `AHC_CARDBUS_DEFAULT_SCSI_ID' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_AHC_CARDBUS_DEFAULT_SCSI_ID
 .global _KERNEL_OPT_AHC_CARDBUS_DEFAULT_SCSI_ID
 .equiv _KERNEL_OPT_AHC_CARDBUS_DEFAULT_SCSI_ID,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_AHC_CARDBUS_DEFAULT_SCSI_ID\n .global _KERNEL_OPT_AHC_CARDBUS_DEFAULT_SCSI_ID\n .equiv _KERNEL_OPT_AHC_CARDBUS_DEFAULT_SCSI_ID,0x6e074def\n .endif");
#endif
