/* option `ISICPCMCIA_SBSPEEDSTAR2' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_ISICPCMCIA_SBSPEEDSTAR2
 .global _KERNEL_OPT_ISICPCMCIA_SBSPEEDSTAR2
 .equiv _KERNEL_OPT_ISICPCMCIA_SBSPEEDSTAR2,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_ISICPCMCIA_SBSPEEDSTAR2\n .global _KERNEL_OPT_ISICPCMCIA_SBSPEEDSTAR2\n .equiv _KERNEL_OPT_ISICPCMCIA_SBSPEEDSTAR2,0x6e074def\n .endif");
#endif
/* option `ISICPCMCIA_ELSA_MCALL' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_ISICPCMCIA_ELSA_MCALL
 .global _KERNEL_OPT_ISICPCMCIA_ELSA_MCALL
 .equiv _KERNEL_OPT_ISICPCMCIA_ELSA_MCALL,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_ISICPCMCIA_ELSA_MCALL\n .global _KERNEL_OPT_ISICPCMCIA_ELSA_MCALL\n .equiv _KERNEL_OPT_ISICPCMCIA_ELSA_MCALL,0x6e074def\n .endif");
#endif
/* option `ISICPCMCIA_ELSA_ISDNMC' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_ISICPCMCIA_ELSA_ISDNMC
 .global _KERNEL_OPT_ISICPCMCIA_ELSA_ISDNMC
 .equiv _KERNEL_OPT_ISICPCMCIA_ELSA_ISDNMC,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_ISICPCMCIA_ELSA_ISDNMC\n .global _KERNEL_OPT_ISICPCMCIA_ELSA_ISDNMC\n .equiv _KERNEL_OPT_ISICPCMCIA_ELSA_ISDNMC,0x6e074def\n .endif");
#endif
/* option `ISICPCMCIA_AVM_A1' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_ISICPCMCIA_AVM_A1
 .global _KERNEL_OPT_ISICPCMCIA_AVM_A1
 .equiv _KERNEL_OPT_ISICPCMCIA_AVM_A1,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_ISICPCMCIA_AVM_A1\n .global _KERNEL_OPT_ISICPCMCIA_AVM_A1\n .equiv _KERNEL_OPT_ISICPCMCIA_AVM_A1,0x6e074def\n .endif");
#endif
