#define	PCDISPLAY_SOFTCURSOR	1
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PCDISPLAY_SOFTCURSOR
 .global _KERNEL_OPT_PCDISPLAY_SOFTCURSOR
 .equiv _KERNEL_OPT_PCDISPLAY_SOFTCURSOR,0x1
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PCDISPLAY_SOFTCURSOR\n .global _KERNEL_OPT_PCDISPLAY_SOFTCURSOR\n .equiv _KERNEL_OPT_PCDISPLAY_SOFTCURSOR,0x1\n .endif");
#endif
