/* option `PCIIDE_I31244_DISABLEDMA' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PCIIDE_I31244_DISABLEDMA
 .global _KERNEL_OPT_PCIIDE_I31244_DISABLEDMA
 .equiv _KERNEL_OPT_PCIIDE_I31244_DISABLEDMA,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PCIIDE_I31244_DISABLEDMA\n .global _KERNEL_OPT_PCIIDE_I31244_DISABLEDMA\n .equiv _KERNEL_OPT_PCIIDE_I31244_DISABLEDMA,0x6e074def\n .endif");
#endif
/* option `PCIIDE_CMD0646U_ENABLEUDMA' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PCIIDE_CMD0646U_ENABLEUDMA
 .global _KERNEL_OPT_PCIIDE_CMD0646U_ENABLEUDMA
 .equiv _KERNEL_OPT_PCIIDE_CMD0646U_ENABLEUDMA,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PCIIDE_CMD0646U_ENABLEUDMA\n .global _KERNEL_OPT_PCIIDE_CMD0646U_ENABLEUDMA\n .equiv _KERNEL_OPT_PCIIDE_CMD0646U_ENABLEUDMA,0x6e074def\n .endif");
#endif
/* option `PCIIDE_AMD756_ENABLEDMA' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PCIIDE_AMD756_ENABLEDMA
 .global _KERNEL_OPT_PCIIDE_AMD756_ENABLEDMA
 .equiv _KERNEL_OPT_PCIIDE_AMD756_ENABLEDMA,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PCIIDE_AMD756_ENABLEDMA\n .global _KERNEL_OPT_PCIIDE_AMD756_ENABLEDMA\n .equiv _KERNEL_OPT_PCIIDE_AMD756_ENABLEDMA,0x6e074def\n .endif");
#endif
/* option `PCIIDE_CMD064x_DISABLE' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PCIIDE_CMD064x_DISABLE
 .global _KERNEL_OPT_PCIIDE_CMD064x_DISABLE
 .equiv _KERNEL_OPT_PCIIDE_CMD064x_DISABLE,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PCIIDE_CMD064x_DISABLE\n .global _KERNEL_OPT_PCIIDE_CMD064x_DISABLE\n .equiv _KERNEL_OPT_PCIIDE_CMD064x_DISABLE,0x6e074def\n .endif");
#endif
