#define	PCKBD_CNATTACH_MAY_FAIL	1
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL
 .global _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL
 .equiv _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL,0x1
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL\n .global _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL\n .equiv _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL,0x1\n .endif");
#endif
