/* option `DKWEDGE_METHOD_APPLE' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_DKWEDGE_METHOD_APPLE
 .global _KERNEL_OPT_DKWEDGE_METHOD_APPLE
 .equiv _KERNEL_OPT_DKWEDGE_METHOD_APPLE,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_DKWEDGE_METHOD_APPLE\n .global _KERNEL_OPT_DKWEDGE_METHOD_APPLE\n .equiv _KERNEL_OPT_DKWEDGE_METHOD_APPLE,0x6e074def\n .endif");
#endif
/* option `DKWEDGE_METHOD_MBR' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_DKWEDGE_METHOD_MBR
 .global _KERNEL_OPT_DKWEDGE_METHOD_MBR
 .equiv _KERNEL_OPT_DKWEDGE_METHOD_MBR,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_DKWEDGE_METHOD_MBR\n .global _KERNEL_OPT_DKWEDGE_METHOD_MBR\n .equiv _KERNEL_OPT_DKWEDGE_METHOD_MBR,0x6e074def\n .endif");
#endif
#define	DKWEDGE_METHOD_GPT	1
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_DKWEDGE_METHOD_GPT
 .global _KERNEL_OPT_DKWEDGE_METHOD_GPT
 .equiv _KERNEL_OPT_DKWEDGE_METHOD_GPT,0x1
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_DKWEDGE_METHOD_GPT\n .global _KERNEL_OPT_DKWEDGE_METHOD_GPT\n .equiv _KERNEL_OPT_DKWEDGE_METHOD_GPT,0x1\n .endif");
#endif
/* option `DKWEDGE_METHOD_BSDLABEL' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_DKWEDGE_METHOD_BSDLABEL
 .global _KERNEL_OPT_DKWEDGE_METHOD_BSDLABEL
 .equiv _KERNEL_OPT_DKWEDGE_METHOD_BSDLABEL,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_DKWEDGE_METHOD_BSDLABEL\n .global _KERNEL_OPT_DKWEDGE_METHOD_BSDLABEL\n .equiv _KERNEL_OPT_DKWEDGE_METHOD_BSDLABEL,0x6e074def\n .endif");
#endif
#define	DKWEDGE_AUTODISCOVER	1
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_DKWEDGE_AUTODISCOVER
 .global _KERNEL_OPT_DKWEDGE_AUTODISCOVER
 .equiv _KERNEL_OPT_DKWEDGE_AUTODISCOVER,0x1
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_DKWEDGE_AUTODISCOVER\n .global _KERNEL_OPT_DKWEDGE_AUTODISCOVER\n .equiv _KERNEL_OPT_DKWEDGE_AUTODISCOVER,0x1\n .endif");
#endif
