/* option `NAMECACHE_ENTER_REVERSE' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_NAMECACHE_ENTER_REVERSE
 .global _KERNEL_OPT_NAMECACHE_ENTER_REVERSE
 .equiv _KERNEL_OPT_NAMECACHE_ENTER_REVERSE,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_NAMECACHE_ENTER_REVERSE\n .global _KERNEL_OPT_NAMECACHE_ENTER_REVERSE\n .equiv _KERNEL_OPT_NAMECACHE_ENTER_REVERSE,0x6e074def\n .endif");
#endif
