/* option `GTTWSI_ALLWINNER' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_GTTWSI_ALLWINNER
 .global _KERNEL_OPT_GTTWSI_ALLWINNER
 .equiv _KERNEL_OPT_GTTWSI_ALLWINNER,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_GTTWSI_ALLWINNER\n .global _KERNEL_OPT_GTTWSI_ALLWINNER\n .equiv _KERNEL_OPT_GTTWSI_ALLWINNER,0x6e074def\n .endif");
#endif
