/* option `VOYAGERFB_ANTIALIAS' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_VOYAGERFB_ANTIALIAS
 .global _KERNEL_OPT_VOYAGERFB_ANTIALIAS
 .equiv _KERNEL_OPT_VOYAGERFB_ANTIALIAS,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_VOYAGERFB_ANTIALIAS\n .global _KERNEL_OPT_VOYAGERFB_ANTIALIAS\n .equiv _KERNEL_OPT_VOYAGERFB_ANTIALIAS,0x6e074def\n .endif");
#endif
/* option `VOYAGERFB_DEBUG' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_VOYAGERFB_DEBUG
 .global _KERNEL_OPT_VOYAGERFB_DEBUG
 .equiv _KERNEL_OPT_VOYAGERFB_DEBUG,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_VOYAGERFB_DEBUG\n .global _KERNEL_OPT_VOYAGERFB_DEBUG\n .equiv _KERNEL_OPT_VOYAGERFB_DEBUG,0x6e074def\n .endif");
#endif
/* option `VOYAGERFB_DEPTH_32' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_VOYAGERFB_DEPTH_32
 .global _KERNEL_OPT_VOYAGERFB_DEPTH_32
 .equiv _KERNEL_OPT_VOYAGERFB_DEPTH_32,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_VOYAGERFB_DEPTH_32\n .global _KERNEL_OPT_VOYAGERFB_DEPTH_32\n .equiv _KERNEL_OPT_VOYAGERFB_DEPTH_32,0x6e074def\n .endif");
#endif
