#define	WI_PCMCIA_SPECTRUM24T_FW	1
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_WI_PCMCIA_SPECTRUM24T_FW
 .global _KERNEL_OPT_WI_PCMCIA_SPECTRUM24T_FW
 .equiv _KERNEL_OPT_WI_PCMCIA_SPECTRUM24T_FW,0x1
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_WI_PCMCIA_SPECTRUM24T_FW\n .global _KERNEL_OPT_WI_PCMCIA_SPECTRUM24T_FW\n .equiv _KERNEL_OPT_WI_PCMCIA_SPECTRUM24T_FW,0x1\n .endif");
#endif
