#define	NSYSMON_POWER	1
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_NSYSMON_POWER
 .global _KERNEL_OPT_NSYSMON_POWER
 .equiv _KERNEL_OPT_NSYSMON_POWER,0x1
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_NSYSMON_POWER\n .global _KERNEL_OPT_NSYSMON_POWER\n .equiv _KERNEL_OPT_NSYSMON_POWER,0x1\n .endif");
#endif
