#define	NSYSMON_TASKQ	1
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_NSYSMON_TASKQ
 .global _KERNEL_OPT_NSYSMON_TASKQ
 .equiv _KERNEL_OPT_NSYSMON_TASKQ,0x1
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_NSYSMON_TASKQ\n .global _KERNEL_OPT_NSYSMON_TASKQ\n .equiv _KERNEL_OPT_NSYSMON_TASKQ,0x1\n .endif");
#endif
