#define	NUNICHROMEFB	0
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_NUNICHROMEFB
 .global _KERNEL_OPT_NUNICHROMEFB
 .equiv _KERNEL_OPT_NUNICHROMEFB,0x0
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_NUNICHROMEFB\n .global _KERNEL_OPT_NUNICHROMEFB\n .equiv _KERNEL_OPT_NUNICHROMEFB,0x0\n .endif");
#endif
